import 'package:flutter/material.dart';

/// Maps a root category's Arabic name to a Material icon, rendered solid
/// gold as the category's own shape (no badge/container) — the glyph itself
/// is the brand mark, not a decoration around it.
/// Matched by keyword (not exact string) so small backend wording changes
/// don't silently fall back to the generic icon. Order matters — first
/// match wins, so put more specific keywords before broader ones.
IconData iconForCategory(String nameAr) {
  for (final entry in _keywordIcons) {
    if (nameAr.contains(entry.$1)) return entry.$2;
  }
  return Icons.storefront_rounded;
}

/// Same idea as [iconForCategory] but for a specialty (category child) —
/// "ورشة أثاث ونجارة", "عيادة", "مطعم" — a much larger and more varied
/// vocabulary (200+ names) than the 21 root categories, so this list is
/// necessarily longer and coarser-grained; the same tolerant keyword match
/// and generic fallback apply, so a name this list doesn't recognize yet
/// still renders something reasonable instead of breaking.
IconData iconForCategoryChild(String nameAr) {
  for (final entry in _childKeywordIcons) {
    if (nameAr.contains(entry.$1)) return entry.$2;
  }
  return Icons.storefront_rounded;
}

const _childKeywordIcons = <(String, IconData)>[
  // Food & drink
  ('مطعم', Icons.restaurant_rounded),
  ('مخابز', Icons.bakery_dining_rounded),
  ('حلويات', Icons.cake_rounded),
  ('كافيه', Icons.local_cafe_rounded),
  ('بن', Icons.local_cafe_rounded),
  ('قهوة', Icons.local_cafe_rounded),
  ('عصائر', Icons.local_bar_rounded),
  ('جزارة', Icons.kebab_dining_rounded),
  ('دواجن', Icons.egg_rounded),
  ('أسماك', Icons.set_meal_rounded),
  ('مزارع سمكية', Icons.set_meal_rounded),
  ('خضار وفاكهة', Icons.eco_rounded),
  ('حبوب وغلال', Icons.grass_rounded),
  ('مجمدات', Icons.ac_unit_rounded),
  ('أكل بيتى', Icons.soup_kitchen_rounded),
  ('مواد غذائية', Icons.local_grocery_store_rounded),
  ('هايبر ماركت', Icons.local_grocery_store_rounded),
  ('سوبر ماركت', Icons.local_grocery_store_rounded),
  ('مني ماركت', Icons.local_grocery_store_rounded),
  ('مكملات غذائية', Icons.medication_liquid_rounded),
  // Home, furniture & decor
  ('نجار', Icons.chair_rounded),
  ('منجد', Icons.chair_rounded),
  ('أثاث', Icons.chair_rounded),
  ('آثاث', Icons.chair_rounded),
  ('مفروشات', Icons.weekend_rounded),
  ('ستائر', Icons.curtains_closed_rounded),
  ('ديكور', Icons.format_paint_rounded),
  ('نقاش', Icons.format_paint_rounded),
  ('جبس', Icons.format_paint_rounded),
  ('محارة', Icons.format_paint_rounded),
  ('نجف', Icons.light_rounded),
  ('باب وشباك', Icons.door_front_door_rounded),
  ('ألمونتال', Icons.window_rounded),
  ('الوميتال', Icons.window_rounded),
  ('زجاج', Icons.window_rounded),
  ('سجاد', Icons.texture_rounded),
  ('باركيه', Icons.texture_rounded),
  ('سيراميك', Icons.grid_on_rounded),
  ('رخام', Icons.grid_on_rounded),
  ('طوب', Icons.foundation_rounded),
  ('اسمنت', Icons.foundation_rounded),
  ('حديد تسليح', Icons.foundation_rounded),
  ('نباتات', Icons.local_florist_rounded),
  ('خدمات نظافة', Icons.cleaning_services_rounded),
  ('منظفات', Icons.cleaning_services_rounded),
  // Repair, trades & construction
  ('تبريد وتكييف', Icons.ac_unit_rounded),
  ('صيانة أجهزة', Icons.build_rounded),
  ('كهربائي', Icons.electrical_services_rounded),
  ('كهرياء', Icons.electrical_services_rounded),
  ('كهرباء', Icons.electrical_services_rounded),
  ('سباك', Icons.plumbing_rounded),
  ('حداد', Icons.hardware_rounded),
  ('نجار', Icons.hardware_rounded),
  ('ورشة', Icons.construction_rounded),
  ('عامل بناء', Icons.construction_rounded),
  ('مقاولات', Icons.construction_rounded),
  ('مبلط', Icons.construction_rounded),
  ('تكسير ونحت', Icons.construction_rounded),
  ('معدات ثقيلة', Icons.precision_manufacturing_rounded),
  ('مصاعد', Icons.elevator_rounded),
  ('حدايد وبويات', Icons.hardware_rounded),
  // Vehicles & transport
  ('سيارات', Icons.directions_car_rounded),
  ('سيارة', Icons.directions_car_rounded),
  ('جنوط وكاوتش', Icons.tire_repair_rounded),
  ('موتوسيكلات', Icons.two_wheeler_rounded),
  ('نقل ركاب', Icons.airport_shuttle_rounded),
  ('ليموزين', Icons.airport_shuttle_rounded),
  ('سائق', Icons.airport_shuttle_rounded),
  ('ونش', Icons.local_shipping_rounded),
  ('مندوب', Icons.delivery_dining_rounded),
  ('كرڤان', Icons.rv_hookup_rounded),
  ('رحلات ومراكب', Icons.directions_boat_rounded),
  ('بوت نيلي', Icons.directions_boat_rounded),
  // Health & medical
  ('مستشفى', Icons.local_hospital_rounded),
  ('عيادة', Icons.local_hospital_rounded),
  ('مركز طبي', Icons.local_hospital_rounded),
  ('مراكز أشعة', Icons.medical_services_rounded),
  ('معمل تحاليل', Icons.biotech_rounded),
  ('صيدلية', Icons.local_pharmacy_rounded),
  ('مواد دوائية', Icons.local_pharmacy_rounded),
  ('مستلزمات طبية', Icons.medical_services_rounded),
  ('حجامة', Icons.healing_rounded),
  // Beauty & personal care
  ('كوافير', Icons.content_cut_rounded),
  ('تجميل', Icons.face_retouching_natural_rounded),
  ('عطور', Icons.spa_rounded),
  // Sports, fitness & entertainment
  ('جيم', Icons.fitness_center_rounded),
  ('نادي رياضي', Icons.fitness_center_rounded),
  ('أكاديمية رياضية', Icons.fitness_center_rounded),
  ('أجهزة رياضية', Icons.fitness_center_rounded),
  ('ملاعب', Icons.sports_soccer_rounded),
  ('حمام سباحة', Icons.pool_rounded),
  ('اكوا بارك', Icons.pool_rounded),
  ('بلياردو', Icons.sports_bar_rounded),
  ('بولينج', Icons.sports_bar_rounded),
  ('بلاي ستيشن', Icons.sports_esports_rounded),
  ('بلايستيشن', Icons.sports_esports_rounded),
  ('مركز ترفيهي', Icons.celebration_rounded),
  ('صالة ألعاب', Icons.sports_esports_rounded),
  ('منطقة أطفال', Icons.child_friendly_rounded),
  ('لعب أطفال', Icons.toys_rounded),
  ('حضانات', Icons.child_care_rounded),
  ('مدرب', Icons.sports_rounded),
  ('لاعبين', Icons.sports_rounded),
  ('ناشئ موهوب', Icons.sports_rounded),
  // Events, hospitality & real estate
  ('تنسيق حفلات', Icons.celebration_rounded),
  ('قاعة مناسبات', Icons.celebration_rounded),
  ('مؤتمرات', Icons.groups_rounded),
  ('مأذون', Icons.celebration_rounded),
  ('فندق', Icons.hotel_rounded),
  ('منتجع', Icons.hotel_rounded),
  ('نُزل', Icons.hotel_rounded),
  ('بيت ضيافة', Icons.hotel_rounded),
  ('مكتب عقاري', Icons.home_work_rounded),
  ('مطور عقاري', Icons.home_work_rounded),
  ('مالك عقار', Icons.home_work_rounded),
  ('مصيفية', Icons.home_work_rounded),
  ('جراج', Icons.garage_rounded),
  ('منطقة عمل مشتركة', Icons.meeting_room_rounded),
  // Professional & office services
  ('محاسبة', Icons.calculate_rounded),
  ('دعاية وإعلان', Icons.campaign_rounded),
  ('محاماه', Icons.gavel_rounded),
  ('تخليص جمركي', Icons.local_shipping_rounded),
  ('استيراد وتصدير', Icons.public_rounded),
  ('صرافة', Icons.currency_exchange_rounded),
  ('تأمين', Icons.shield_rounded),
  ('تسويق', Icons.campaign_rounded),
  ('هندسية', Icons.engineering_rounded),
  ('أدوات مكتبية', Icons.edit_note_rounded),
  ('مكتب', Icons.business_center_rounded),
  ('شركة', Icons.apartment_rounded),
  ('إتصالات', Icons.cell_tower_rounded),
  ('كمبيوتر', Icons.computer_rounded),
  ('برمجة', Icons.code_rounded),
  ('برمجيات', Icons.code_rounded),
  ('استوديوهات', Icons.camera_alt_rounded),
  ('فوتوجرافر', Icons.camera_alt_rounded),
  ('طباعة', Icons.print_rounded),
  ('تعبئة وتغليف', Icons.inventory_2_rounded),
  ('أمن', Icons.security_rounded),
  ('سيفتى', Icons.security_rounded),
  ('دش وأقمار صناعية', Icons.satellite_alt_rounded),
  ('سنتر دروس', Icons.school_rounded),
  ('قاعات تدريب', Icons.school_rounded),
  ('مركز تدريب', Icons.school_rounded),
  // Retail & goods
  ('ملابس', Icons.checkroom_rounded),
  ('أقمشة', Icons.checkroom_rounded),
  ('أصواف', Icons.checkroom_rounded),
  ('جلود وشنط وأحذية', Icons.checkroom_rounded),
  ('اكسسوار', Icons.diamond_rounded),
  ('ذهب', Icons.diamond_rounded),
  ('فضة', Icons.diamond_rounded),
  ('نظارات', Icons.visibility_rounded),
  ('كتب', Icons.menu_book_rounded),
  ('أنتيكات وتحف', Icons.museum_rounded),
  ('زراع', Icons.agriculture_rounded),
  ('أعلاف', Icons.agriculture_rounded),
  ('مواشي وأرانب', Icons.agriculture_rounded),
  ('مزارع', Icons.agriculture_rounded),
  ('مشتقات التدخين', Icons.smoking_rooms_rounded),
  ('بلاستيك', Icons.category_rounded),
  ('إسفنج', Icons.category_rounded),
  ('قطع غيار', Icons.build_circle_rounded),
  ('أدوات كهربائية', Icons.electrical_services_rounded),
  ('أجهزة كهربائية', Icons.electrical_services_rounded),
  ('كابلات وقواطع', Icons.electrical_services_rounded),
];

const _keywordIcons = <(String, IconData)>[
  ('مطاعم', Icons.restaurant_rounded),
  ('كافيه', Icons.local_cafe_rounded),
  ('فندق', Icons.hotel_rounded),
  ('سياح', Icons.hotel_rounded),
  ('مصنع', Icons.factory_rounded),
  ('مصانع', Icons.factory_rounded),
  ('شرك', Icons.apartment_rounded),
  ('مكاتب', Icons.business_rounded),
  ('صحة', Icons.local_hospital_rounded),
  ('طبي', Icons.local_hospital_rounded),
  ('معارض', Icons.event_rounded),
  ('محلات', Icons.shopping_bag_rounded),
  ('اونلاين', Icons.shopping_cart_rounded),
  ('أونلاين', Icons.shopping_cart_rounded),
  ('عقارات', Icons.home_work_rounded),
  ('أراضي', Icons.home_work_rounded),
  ('سيارات', Icons.directions_car_rounded),
  ('فنون', Icons.palette_rounded),
  ('ترفي', Icons.palette_rounded),
  ('تكنولوجيا', Icons.memory_rounded),
  ('رياض', Icons.fitness_center_rounded),
  ('قاعات', Icons.celebration_rounded),
  ('دورات', Icons.school_rounded),
  ('تدريب', Icons.school_rounded),
  ('ورش', Icons.construction_rounded),
  ('صيانة', Icons.construction_rounded),
  ('زراع', Icons.agriculture_rounded),
  ('حيوان', Icons.pets_rounded),
  ('ملابس', Icons.checkroom_rounded),
  ('اكسسوارات', Icons.checkroom_rounded),
  ('كوافير', Icons.content_cut_rounded),
  ('شحن', Icons.local_shipping_rounded),
  ('توصيل', Icons.local_shipping_rounded),
  ('مهن', Icons.engineering_rounded),
  ('حرفي', Icons.engineering_rounded),
];
